// <auto-generated />
namespace HgWorkflow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newFieldAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newFieldAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201908201918150_newFieldAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
